Demo 2.0/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Demo_2._0.Models;

namespace Demo_2._0.Controllers
{
    public class RequestsController : Controller
    {
        private inGravureEntities db = new inGravureEntities();

        // GET: Requests
        public ViewResult Index(string sortOrder, string searchString)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            var requests = from s in db.po_avise_requests
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                requests = requests.Where(s => s.Besteller.Contains(searchString)
                                       || s.Besteller.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    requests = requests.OrderByDescending(s => s.Besteller);
                    break;
                case "Date":
                    requests= requests.OrderBy(s => s.Zeitpunkt);
                    break;
                case "date_desc":
                    requests = requests.OrderByDescending(s => s.Zeitpunkt);
                    break;
                default:
                    requests = requests.OrderBy(s => s.Besteller);
                    break;
            }

            return View(requests.ToList());
        }

        // GET: Requests/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            po_avise_requests po_avise_requests = db.po_avise_requests.Find(id);
            if (po_avise_requests == null)
            {
                return HttpNotFound();
            }
            return View(po_avise_requests);
        }

        // GET: Requests/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Requests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "uid,po_no,Zeitpunkt,Besteller,item_description,off_loading_advise,Entladung,status")] po_avise_requests po_avise_requests)
        {
            if (ModelState.IsValid)
            {
                po_avise_requests.uid = Guid.NewGuid();
                db.po_avise_requests.Add(po_avise_requests);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(po_avise_requests);
        }

        // GET: Requests/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            po_avise_requests po_avise_requests = db.po_avise_requests.Find(id);
            if (po_avise_requests == null)
            {
                return HttpNotFound();
            }
            return View(po_avise_requests);
        }

        // POST: Requests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "uid,po_no,Zeitpunkt,Besteller,item_description,off_loading_advise,Entladung,status")] po_avise_requests po_avise_requests)
        {
            if (ModelState.IsValid)
            {
                db.Entry(po_avise_requests).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(po_avise_requests);
        }

        // GET: Requests/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            po_avise_requests po_avise_requests = db.po_avise_requests.Find(id);
            if (po_avise_requests == null)
            {
                return HttpNotFound();
            }
            return View(po_avise_requests);
        }

        // POST: Requests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            po_avise_requests po_avise_requests = db.po_avise_requests.Find(id);
            db.po_avise_requests.Remove(po_avise_requests);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Demo 2.0/Controllers/TransportationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Demo_2._0.Models
{
    public class TransportationsController : Controller
    {
        private inGravureEntities4 db = new inGravureEntities4();

        // GET: Transportations
        public ActionResult Index()
        {
            return View(db.po_avise_transportations.ToList());
        }

        // GET: Transportations/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            po_avise_transportations po_avise_transportations = db.po_avise_transportations.Find(id);
            if (po_avise_transportations == null)
            {
                return HttpNotFound();
            }
            return View(po_avise_transportations);
        }

        // GET: Transportations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Transportations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "uid,po_avise_request_uid,transportation_id,delivery_date,clock_timing,number,means_of_transportation,material,state")] po_avise_transportations po_avise_transportations)
        {
            if (ModelState.IsValid)
            {
                po_avise_transportations.uid = Guid.NewGuid();
                db.po_avise_transportations.Add(po_avise_transportations);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(po_avise_transportations);
        }

        // GET: Transportations/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            po_avise_transportations po_avise_transportations = db.po_avise_transportations.Find(id);
            if (po_avise_transportations == null)
            {
                return HttpNotFound();
            }
            return View(po_avise_transportations);
        }

        // POST: Transportations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "uid,po_avise_request_uid,transportation_id,delivery_date,clock_timing,number,means_of_transportation,material,state")] po_avise_transportations po_avise_transportations)
        {
            if (ModelState.IsValid)
            {
                db.Entry(po_avise_transportations).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(po_avise_transportations);
        }

        // GET: Transportations/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            po_avise_transportations po_avise_transportations = db.po_avise_transportations.Find(id);
            if (po_avise_transportations == null)
            {
                return HttpNotFound();
            }
            return View(po_avise_transportations);
        }

        // POST: Transportations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            po_avise_transportations po_avise_transportations = db.po_avise_transportations.Find(id);
            db.po_avise_transportations.Remove(po_avise_transportations);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Demo 2.0/Views/Transportations/Create.cshtml
@model Demo_2._0.Models.po_avise_transportations

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>po_avise_transportations</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.po_avise_request_uid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.po_avise_request_uid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.po_avise_request_uid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.transportation_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.transportation_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.transportation_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.delivery_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.delivery_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.delivery_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.clock_timing, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.clock_timing, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.clock_timing, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.means_of_transportation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.means_of_transportation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.means_of_transportation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.material, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.material, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.material, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.state, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.state, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.state, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Demo 2.0/Views/Transportations/Delete.cshtml
@model Demo_2._0.Models.po_avise_transportations

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>po_avise_transportations</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.po_avise_request_uid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.po_avise_request_uid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.transportation_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.transportation_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.delivery_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.delivery_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.clock_timing)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.clock_timing)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.means_of_transportation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.means_of_transportation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.material)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.material)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.state)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.state)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Demo 2.0/Views/Transportations/Details.cshtml
@model Demo_2._0.Models.po_avise_transportations

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>po_avise_transportations</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.po_avise_request_uid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.po_avise_request_uid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.transportation_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.transportation_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.delivery_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.delivery_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.clock_timing)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.clock_timing)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.means_of_transportation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.means_of_transportation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.material)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.material)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.state)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.state)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.uid }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Demo 2.0/Views/Transportations/Edit.cshtml
@model Demo_2._0.Models.po_avise_transportations

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>po_avise_transportations</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.uid)

        <div class="form-group">
            @Html.LabelFor(model => model.po_avise_request_uid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.po_avise_request_uid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.po_avise_request_uid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.transportation_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.transportation_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.transportation_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.delivery_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.delivery_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.delivery_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.clock_timing, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.clock_timing, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.clock_timing, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.means_of_transportation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.means_of_transportation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.means_of_transportation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.material, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.material, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.material, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.state, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.state, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.state, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Demo 2.0/Views/Transportations/Index.cshtml
@model IEnumerable<Demo_2._0.Models.po_avise_transportations>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.po_avise_request_uid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.transportation_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.delivery_date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.clock_timing)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.means_of_transportation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.material)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.state)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.po_avise_request_uid)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.transportation_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.delivery_date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.clock_timing)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.number)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.means_of_transportation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.material)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.state)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.uid }) |
            @Html.ActionLink("Details", "Details", new { id = item.uid }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.uid })
        </td>
        <td>
            @Html.ActionLink("Back to Avisierung", "Index", "Requests")
        </td>
        
    </tr>
}

</table>