Demo 2.0/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Demo_2._0.Models;

namespace Demo_2._0.Controllers
{
    public class RequestsController : Controller
    {
        private inGravureEntities db = new inGravureEntities();

        // GET: Requests
        public ViewResult Index(string sortOrder, string searchString)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            var requests = from s in db.po_avise_requests
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                requests = requests.Where(s => s.Besteller.Contains(searchString)
                                       || s.Besteller.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    requests = requests.OrderByDescending(s => s.Besteller);
                    break;
                case "Date":
                    requests= requests.OrderBy(s => s.Zeitpunkt);
                    break;
                case "date_desc":
                    requests = requests.OrderByDescending(s => s.Zeitpunkt);
                    break;
                default:
                    requests = requests.OrderBy(s => s.Besteller);
                    break;
            }

            return View(requests.ToList());
        }

        // GET: Requests/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            po_avise_requests po_avise_requests = db.po_avise_requests.Find(id);
            if (po_avise_requests == null)
            {
                return HttpNotFound();
            }
            return View(po_avise_requests);
        }

        // GET: Requests/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Requests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "uid,po_no,Zeitpunkt,Besteller,item_description,off_loading_advise,Entladung,status")] po_avise_requests po_avise_requests)
        {
            if (ModelState.IsValid)
            {
                po_avise_requests.uid = Guid.NewGuid();
                db.po_avise_requests.Add(po_avise_requests);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(po_avise_requests);
        }

        // GET: Requests/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            po_avise_requests po_avise_requests = db.po_avise_requests.Find(id);
            if (po_avise_requests == null)
            {
                return HttpNotFound();
            }
            return View(po_avise_requests);
        }

        // POST: Requests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "uid,po_no,Zeitpunkt,Besteller,item_description,off_loading_advise,Entladung,status")] po_avise_requests po_avise_requests)
        {
            if (ModelState.IsValid)
            {
                db.Entry(po_avise_requests).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(po_avise_requests);
        }

        // GET: Requests/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            po_avise_requests po_avise_requests = db.po_avise_requests.Find(id);
            if (po_avise_requests == null)
            {
                return HttpNotFound();
            }
            return View(po_avise_requests);
        }

        // POST: Requests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            po_avise_requests po_avise_requests = db.po_avise_requests.Find(id);
            db.po_avise_requests.Remove(po_avise_requests);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Demo 2.0/Controllers/TransportationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Demo_2._0.Models
{
    public class TransportationsController : Controller
    {
        private inGravureEntities4 db = new inGravureEntities4();

        // GET: Transportations
        public ActionResult Index()
        {
            return View(db.po_avise_transportations.ToList());
        }

        // GET: Transportations/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            po_avise_transportations po_avise_transportations = db.po_avise_transportations.Find(id);
            if (po_avise_transportations == null)
            {
                return HttpNotFound();
            }
            return View(po_avise_transportations);
        }

        // GET: Transportations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Transportations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "uid,po_avise_request_uid,transportation_id,delivery_date,clock_timing,number,means_of_transportation,material,state")] po_avise_transportations po_avise_transportations)
        {
            if (ModelState.IsValid)
            {
                po_avise_transportations.uid = Guid.NewGuid();
                db.po_avise_transportations.Add(po_avise_transportations);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(po_avise_transportations);
        }

        // GET: Transportations/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            po_avise_transportations po_avise_transportations = db.po_avise_transportations.Find(id);
            if (po_avise_transportations == null)
            {
                return HttpNotFound();
            }
            return View(po_avise_transportations);
        }

        // POST: Transportations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "uid,po_avise_request_uid,transportation_id,delivery_date,clock_timing,number,means_of_transportation,material,state")] po_avise_transportations po_avise_transportations)
        {
            if (ModelState.IsValid)
            {
                db.Entry(po_avise_transportations).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(po_avise_transportations);
        }

        // GET: Transportations/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            po_avise_transportations po_avise_transportations = db.po_avise_transportations.Find(id);
            if (po_avise_transportations == null)
            {
                return HttpNotFound();
            }
            return View(po_avise_transportations);
        }

        // POST: Transportations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            po_avise_transportations po_avise_transportations = db.po_avise_transportations.Find(id);
            db.po_avise_transportations.Remove(po_avise_transportations);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Demo 2.0/Views/Requests/Create.cshtml
@model Demo_2._0.Models.po_avise_requests

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>po_avise_requests</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.po_no, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.po_no, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.po_no, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zeitpunkt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zeitpunkt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zeitpunkt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Besteller, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Besteller, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Besteller, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.item_description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.item_description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.item_description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.off_loading_advise, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.off_loading_advise, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.off_loading_advise, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Entladung, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Entladung, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Entladung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Demo 2.0/Views/Requests/Delete.cshtml
@model Demo_2._0.Models.po_avise_requests

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>po_avise_requests</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.po_no)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.po_no)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zeitpunkt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zeitpunkt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Besteller)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Besteller)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.item_description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.item_description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.off_loading_advise)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.off_loading_advise)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Entladung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Entladung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Demo 2.0/Views/Requests/Details.cshtml
@model Demo_2._0.Models.po_avise_requests

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>po_avise_requests</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.po_no)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.po_no)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zeitpunkt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zeitpunkt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Besteller)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Besteller)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.item_description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.item_description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.off_loading_advise)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.off_loading_advise)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Entladung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Entladung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.uid }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Demo 2.0/Views/Requests/Edit.cshtml
@model Demo_2._0.Models.po_avise_requests

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>po_avise_requests</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.uid)

        <div class="form-group">
            @Html.LabelFor(model => model.po_no, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.po_no, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.po_no, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zeitpunkt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zeitpunkt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zeitpunkt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Besteller, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Besteller, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Besteller, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.item_description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.item_description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.item_description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.off_loading_advise, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.off_loading_advise, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.off_loading_advise, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Entladung, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Entladung, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Entladung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Demo 2.0/Views/Requests/Index.cshtml
@model IEnumerable<Demo_2._0.Models.po_avise_requests>


@{
    ViewBag.Title = "Avisierungen";
}


<h2>Avisierungen</h2>
<p>Current Time @DateTime.Now</p>

<p>
   
</p>


<p>
    @Html.ActionLink("Create New", "Create")
</p>


@using (Html.BeginForm())
{
    <p>
        Find by name: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}

<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.po_no)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Zeitpunkt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Besteller)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.item_description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.off_loading_advise)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Entladung)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.status)
        </th>
        

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.po_no)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zeitpunkt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Besteller)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.item_description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.off_loading_advise)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Entladung)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.status)
            </td>
            <td>
                @Html.ActionLink("Enter Transportation details", "Index", "Transportations")
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.uid }) |
                @Html.ActionLink("Details", "Details", new { id = item.uid }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.uid })
            </td>
        </tr>
    }

</table>