Demo 4.0/Controllers/TransportationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Demo_4._0.Models;

namespace Demo_4._0.Controllers
{
    public class TransportationsController : Controller
    {
        private inGravureEntities db = new inGravureEntities();

        // GET: Transportations
        public ActionResult Index()
        {
            var po_avise_transportations = db.po_avise_transportations.Include(p => p.po_avise_requests);
            return View(po_avise_transportations.ToList());
        }

        // GET: Transportations/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            po_avise_transportations po_avise_transportations = db.po_avise_transportations.Find(id);
            if (po_avise_transportations == null)
            {
                return HttpNotFound();
            }
            return View(po_avise_transportations);
        }

        // GET: Transportations/Create
        public ActionResult Create()
        {
            ViewBag.fk_po_avise_request_uid = new SelectList(db.po_avise_requests, "uid", "uid");
            return View();
        }

        // POST: Transportations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "uid,fk_po_avise_request_uid,start_time,duration,transport_typ,material,qty,uom,state")] po_avise_transportations po_avise_transportations)
        {
            if (ModelState.IsValid)
            {
                po_avise_transportations.uid = Guid.NewGuid();
                db.po_avise_transportations.Add(po_avise_transportations);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.fk_po_avise_request_uid = new SelectList(db.po_avise_requests, "uid", "uid", po_avise_transportations.fk_po_avise_request_uid);
            return View(po_avise_transportations);
        }

        // GET: Transportations/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            po_avise_transportations po_avise_transportations = db.po_avise_transportations.Find(id);
            if (po_avise_transportations == null)
            {
                return HttpNotFound();
            }
            ViewBag.fk_po_avise_request_uid = new SelectList(db.po_avise_requests, "uid", "uid", po_avise_transportations.fk_po_avise_request_uid);
            return View(po_avise_transportations);
        }

        // POST: Transportations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "uid,fk_po_avise_request_uid,start_time,duration,transport_typ,material,qty,uom,state")] po_avise_transportations po_avise_transportations)
        {
            if (ModelState.IsValid)
            {
                db.Entry(po_avise_transportations).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.fk_po_avise_request_uid = new SelectList(db.po_avise_requests, "uid", "uid", po_avise_transportations.fk_po_avise_request_uid);
            return View(po_avise_transportations);
        }

        // GET: Transportations/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            po_avise_transportations po_avise_transportations = db.po_avise_transportations.Find(id);
            if (po_avise_transportations == null)
            {
                return HttpNotFound();
            }
            return View(po_avise_transportations);
        }

        // POST: Transportations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            po_avise_transportations po_avise_transportations = db.po_avise_transportations.Find(id);
            db.po_avise_transportations.Remove(po_avise_transportations);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Demo 4.0/Controllers/po_avise_requestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Demo_4._0.Models;

namespace Demo_4._0.Controllers
{
    public class po_avise_requestsController : Controller
    {
        private inGravureEntities db = new inGravureEntities();

        // GET: po_avise_requests
        public ActionResult Index()
        {
            return View(db.po_avise_requests.ToList());
        }

        // GET: po_avise_requests/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            po_avise_requests po_avise_requests = db.po_avise_requests.Find(id);
            if (po_avise_requests == null)
            {
                return HttpNotFound();
            }
            return View(po_avise_requests);
        }

        // GET: po_avise_requests/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: po_avise_requests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "uid,fk_po_avise_request_uid,material,supplier,qty,uom,unloading")] po_avise_requests po_avise_requests)
        {
            if (ModelState.IsValid)
            {
                po_avise_requests.uid = Guid.NewGuid();
                db.po_avise_requests.Add(po_avise_requests);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(po_avise_requests);
        }

        // GET: po_avise_requests/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            po_avise_requests po_avise_requests = db.po_avise_requests.Find(id);
            if (po_avise_requests == null)
            {
                return HttpNotFound();
            }
            return View(po_avise_requests);
        }

        // POST: po_avise_requests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "uid,fk_po_avise_request_uid,material,supplier,qty,uom,unloading")] po_avise_requests po_avise_requests)
        {
            if (ModelState.IsValid)
            {
                db.Entry(po_avise_requests).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(po_avise_requests);
        }

        // GET: po_avise_requests/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            po_avise_requests po_avise_requests = db.po_avise_requests.Find(id);
            if (po_avise_requests == null)
            {
                return HttpNotFound();
            }
            return View(po_avise_requests);
        }

        // POST: po_avise_requests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            po_avise_requests po_avise_requests = db.po_avise_requests.Find(id);
            db.po_avise_requests.Remove(po_avise_requests);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Demo 4.0/Views/Transportations/Create.cshtml
@model Demo_4._0.Models.po_avise_transportations

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>po_avise_transportations</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       

        <div class="form-group">
            @Html.LabelFor(model => model.start_time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.start_time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.start_time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.transport_typ, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.transport_typ, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.transport_typ, "", new { @class = "text-danger" })
            </div>
        </div>

      
        <div class="form-group">
            @Html.LabelFor(model => model.state, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.state, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.state, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Demo 4.0/Views/Transportations/Delete.cshtml
@model Demo_4._0.Models.po_avise_transportations

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>po_avise_transportations</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.start_time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.start_time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.transport_typ)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.transport_typ)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.material)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.material)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.qty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.qty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.uom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.uom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.state)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.state)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.po_avise_requests.material)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.po_avise_requests.material)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Demo 4.0/Views/Transportations/Details.cshtml
@model Demo_4._0.Models.po_avise_transportations

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>po_avise_transportations</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.start_time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.start_time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.transport_typ)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.transport_typ)
        </dd>

        
        

        <dt>
            @Html.DisplayNameFor(model => model.state)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.state)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.po_avise_requests.material)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.po_avise_requests.material)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.uid }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Demo 4.0/Views/Transportations/Edit.cshtml
@model Demo_4._0.Models.po_avise_transportations

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>po_avise_transportations</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.uid)

        <div class="form-group">
            @Html.LabelFor(model => model.fk_po_avise_request_uid, "fk_po_avise_request_uid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("fk_po_avise_request_uid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.fk_po_avise_request_uid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.start_time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.start_time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.start_time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.transport_typ, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.transport_typ, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.transport_typ, "", new { @class = "text-danger" })
            </div>
        </div>

      

        <div class="form-group">
            @Html.LabelFor(model => model.state, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.state, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.state, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Demo 4.0/Views/Transportations/Index.cshtml
@model IEnumerable<Demo_4._0.Models.po_avise_transportations>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.start_time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.duration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.transport_typ)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.state)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.start_time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.duration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.transport_typ)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.state)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.uid }) |
                @Html.ActionLink("Details", "Details", new { id = item.uid }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.uid })
            </td>
        </tr>
    }

</table>
<td>
    @Html.ActionLink(" Back to request", "Index", "po_avise_requests")
</td>